[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-scripts/jellybeans.vim'
hook_add = '''
  au MyAutoCmd VimEnter * nested colorscheme jellybeans
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'

[[plugins]]
repo = 'h1mesuke/vim-alignta.git'

[[plugins]]
repo = 'nishigori/increment-activator'

[[plugins]]
repo = 'vim-scripts/sudo.vim'
on_cmd = ['SudoWrite', 'SudoRead']

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'alpaca-tc/alpaca_tags'

[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = ['vim-quickrun']

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
