[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'vim-scripts/jellybeans.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'

[[plugins]]
repo = 'delphinus35/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile']

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css']

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = ['less']

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/php.vim'
on_ft = ['php']

[[plugins]]
repo = 'violetyk/cake.vim'
on_ft = ['php']

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'vim-scripts/Markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'superbrothers/vim-vimperator'
on_ft = ['vimperator']

[[plugins]]
repo = 'othree/html5.vim'
