[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'html', 'php']

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = ['javascript']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javascript']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']

[[plugins]]
repo = 'mattn/jscomplete-vim'
on_ft = ['javascript']
hook_add = 'setl omnifunc=jscomplete#CompleteJS'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
on_ft = ['javascript']
hook_add = "
setl omnifunc=jscomplete#CompleteJS \n
if !exists('g:neocomplcache_omni_functions') \n
  let g:neocomplcache_omni_functions = {} \n
  endif \n
  let g:neocomplcache_omni_functions.javascript = 'nodejscomplete#CompleteJS' \n
  let g:node_usejscomplete = 1
"

[[plugins]]
repo = 'digitaltoad/vim-pug.git'
on_ft = ['jade', 'pug']

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css']

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = ['less']

[[plugins]]
repo = 'wavded/vim-stylus.git'

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]]
repo = 'vim-scripts/ruby-matchit'
on_ft = ['ruby']

[[plugins]]
repo    = 'rhysd/vim-textobj-ruby'
depends = ['vim-textobj-user']
on_ft   = ['ruby']

[[plugins]]
repo = 'tpope/vim-rake'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/php.vim'
on_ft = ['php']

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'superbrothers/vim-vimperator'
on_ft = ['vimperator']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
