[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/tabpagebuffer.vim'
on_source = ['unite.vim', 'vimfiler']

[[plugins]]
repo      = 'Shougo/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo      = 'Shougo/vimfiler'
on_source = 'unite.vim'
on_path   = '.*'
on_cmd    = [
    'VimFiler',
    'VimFilerExplorer',
    'Edit',
    'Read',
    'Source',
    'Write',
]

[[plugins]]
repo =  'pasela/unite-fuel'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'ujihisa/neco-look'
depends = ['neocomplete.vim']
on_i = 1

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'vim-scripts/renamer.vim'
on_cmd = ['Rename']
