Encoding:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

AsciiComments:
  Enabled: false

CyclomaticComplexity:
  Max: 20

Documentation:
  Enabled: false

NumericLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/DefWithParentheses:
  AutoCorrect: true

Style/MethodCallWithoutArgsParentheses:
  AutoCorrect: true

Style/MethodDefParentheses:
  AutoCorrect: true

Layout/IndentationWidth:
  AutoCorrect: true

Layout/MultilineOperationIndentation:
  AutoCorrect: true

Layout/EmptyLines:
  AutoCorrect: true

Layout/EmptyLinesAroundAccessModifier:
  AutoCorrect: true

Layout/EmptyLinesAroundBlockBody:
  AutoCorrect: true

Layout/EmptyLinesAroundClassBody:
  AutoCorrect: true

Layout/EmptyLinesAroundMethodBody:
  AutoCorrect: true

Layout/EmptyLinesAroundModuleBody:
  AutoCorrect: true

Layout/TrailingBlankLines:
  AutoCorrect: true

Style/Layout:
  AutoCorrect: true

Style/Layout:
  AutoCorrect: true

Style/Layout:
  AutoCorrect: true

Layout/SpaceAroundEqualsInParameterDefault:
  AutoCorrect: true

Layout/SpaceBeforeSemicolon:
  AutoCorrect: true

Layout/TrailingWhitespace:
  AutoCorrect: true
