[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = 'neomru.vim'
on_event = 'BufRead'
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/unite-outline'
depends = 'denite.nvim'
hook_add = '''
source ~/.config/nvim/plugins/unite-outline.rc.vim
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
depends = 'denite.nvim'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'
depends = 'denite.nvim'
