[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'vim-scripts/renamer.vim'
on_cmd = ['Rename']

[[plugins]]
repo = 'ujihisa/neco-look'
depends = 'deoplete.nvim'
on_i = 1
hook_add = '''
  call dein#add('ujihisa/neco-look')
'''
