[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Gdiffsplit', 'Ggrep', 'Gstatus', 'Gwrite', 'Gcommit']
hook_add = '''
source ~/.config/nvim/plugins/unite-outline.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-rhubarb'
depends = 'vim-fugitive'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
on_cmd = ['Defx']
hook_add ='''
source ~/.config/nvim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'vim-scripts/renamer.vim'
on_cmd = ['Rename']

[[plugins]]
repo = 'h1mesuke/vim-alignta.git'
on_cmd    = ['Align', 'Alignta']
hook_add = '''
source ~/.config/nvim/plugins/vim-alignta.rc.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = 'vimproc.vim'
hook_add = '''
source ~/.config/nvim/plugins/vim-quickrun.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'
depends = 'vim-quickrun'

[[plugins]]
repo = 'vim-scripts/sudo.vim'
on_cmd = ['SudoWrite', 'SudoRead']

