[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = 'async.vim'
hook_add = '''
source ~/.config/nvim/plugins/vim-lsp.rc.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
hook_add = '''
source ~/.config/nvim/plugins/vim-lsp-settings.rc.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'
depends = 'vim-lsp'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'
depends = 'vim-lsp'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-neosnippet'
depends = 'vim-lsp'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = 'vim-lsp'
