[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = 'async.vim'
hook_add = '''
  let g:lsp_signs_enabled = 1
  let g:lsp_diagnostics_enabled = 1
  let g:lsp_diagnostics_echo_cursor = 1
  let g:lsp_virtual_text_enabled = 1
  let g:lsp_text_edit_enabled = 1

  let g:lsp_signs_error = {'text': '✗'}
  let g:lsp_signs_warning = {'text': '‼'}
  let g:lsp_signs_information = {'text': 'i'}
  let g:lsp_signs_hint = {'text': '?'}

  nnoremap [lsp] <Nop>
  nmap <C-e> [lsp]
  nnoremap [lsp]r :<C-u>LspRename<CR>
  nnoremap [lsp]f :<C-u>LspDocumentFormatSync<CR>
  nnoremap [lsp]F :<C-u>LspDocumentDiagnostics<CR>
  nnoremap [lsp]g :<C-u>LspWorkspaceSymbol<CR>

  nmap [lsp]e <C-u>:!eslint --fix "%"<CR>
  nmap [lsp]j <C-u>:!jest "%"<CR>

  nnoremap <C-[> :<C-u>LspReferences<CR>
  nnoremap <C-]> :<C-u>LspDefinition<CR>
  nnoremap K :<C-u>LspHover<CR>
  nmap <C-k> <C-u>:LspPreviousDiagnostic<CR>
  nmap <C-j> <C-u>:LspNextDiagnostic<CR>

  let g:lsp_settings_filetype_javascript = ['typescript-language-server', 'eslint-language-server']
  let g:lsp_settings_filetype_typescript = ['typescript-language-server', 'eslint-language-server']
  let g:lsp_settings_filetype_jsx        = ['typescript-language-server', 'eslint-language-server']
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
hook_add = '''
let g:lsp_settings_servers_dir = g:cache_home.'/dein/repos/github.com/mattn/vim-lsp-settings'
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'
depends = 'vim-lsp'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'
depends = 'vim-lsp'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-neosnippet'
depends = 'vim-lsp'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = 'vim-lsp'
