[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = 'async.vim'
hook_add = '''
source ~/.config/nvim/plugins/vim-lsp.rc.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = 'vim-lsp'
hook_add = '''
source ~/.config/nvim/plugins/vim-lsp-settings.rc.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'
depends = 'vim-lsp'

