[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
 repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
depends = 'context_filetype.vim'
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'
