[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
 repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
depends = 'context_filetype.vim'
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tomtom/tcomment_vim.git'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']

[[plugins]]
repo = 'nishigori/increment-activator'
hook_add = '''
  let g:increment_activator_filetype_candidates = {
  \ '_': [
  \   ['info', 'warning', 'notice', 'error', 'success'],
  \   ['mini', 'small', 'medium', 'large', 'xlarge', 'xxlarge'],
  \   ['static', 'absolute', 'relative', 'fixed', 'sticky'],
  \   ['height', 'width'],
  \   ['left', 'right', 'top', 'bottom'],
  \   ['enable', 'disable'],
  \   ['enabled', 'disabled'],
  \   ['should', 'should_not'],
  \   ['be_file', 'be_directory'],
  \   ['div', 'span'],
  \   ['column', 'row'],
  \   ['start', 'end'],
  \   ['head', 'tail'],
  \   ['get', 'post'],
  \   ['margin', 'padding'],
  \   ['primary', 'secondary', 'tertiary'],
  \   ['development', 'staging', 'production'],
  \ ],
  \ 'ruby': [
  \   ['if', 'unless'],
  \   ['nil', 'empty', 'blank'],
  \   ['string', 'text', 'integer', 'float', 'datetime', 'timestamp', 'timestamp'],
  \ ],
  \ 'javascript': [
  \   ['const', 'let'],
  \   ['props', 'state'],
  \ ],
  \ 'git-rebase-todo': [
  \   ['pick', 'reword', 'edit', 'squash', 'fixup', 'exec'],
  \ ],
  \}
'''
