[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
source ~/.config/nvim/plugins/onedark.rc.vim
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/plugins/iceberg.rc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
depends = 'onedark.vim'
hook_add = '''
source ~/.config/nvim/plugins/vim-indent-guides.rc.vim
'''

[[plugins]]
repo = 'kien/rainbow_parentheses.vim'
hook_add = '''
source ~/.config/nvim/plugins/rainbow_parentheses.rc.vim
'''
